### ISSUE TITLE
GameState

### ISSUE THREAD

**Issue by madson812** [CS-4488-Capstone-Tanks/CS4488-Tanks-Team#35]

**Comment by Dakoziol** [comment]
It's getting there, it can load state from a json file, just waiting on some dependencies to create all the objects. Cannot save state to file yet, I'm guessing that's a bells-and-whistles thing, so for a later issue.
Most of my time has gone toward this class, if I have to give a time, let's say 12 hours

**Comment by Dakoziol** [comment]
~8 hours later, expanded the functionality of the gamestate mostly, including making it a singleton, including methods to get references to gameobjectes, etc. Again, a decent amount of this time was just waiting on builds.

**Comment by Dakoziol** [comment]
~8 hours getting collision detection to work. I'm really guessing here, and most of the work was really getting other classes to play nice, not in the GameState itself. I don't know if the GameState will ever be "done", being the core of the simulation, but I think it's fleshed out enough to close
