### ISSUE TITLE
Implement game over / enemy killed

### ISSUE THREAD

**Issue by madson812** [CS-4488-Capstone-Tanks/CS4488-Tanks-Team#65]

**Comment by Dakoziol** [comment]
This is done, it a quick and dirty technically-functional sort of way. Not that it's messy or spaghetti code or anything, it's just really simple. All in all, I'd say it took 5 hours, most of that just learning how the code in Game worked and debugging it to figure out exactly what was wrong. All in all this took 5 hours, but last I checked it hasn't been merged into develop yet
