### ISSUE TITLE
Have obstacle store obstacle type and render correct obstacle

### ISSUE THREAD

**Issue by madson812** [CS-4488-Capstone-Tanks/CS4488-Tanks-Team#72]
The JSON currently has obstacle types, but the renderer only shows trees. Add variable for obstacle type and link it to the renderer.

**Comment by coxtyson** [comment]
Don't remember precisely, I noted in the discord and the merge request, this collection of features (including other closed issues in this batch) took 6 hours, so something like 4ish on this one? Whatever makes that math check out
